/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AlterarLoginSenhaPanel.java
 *
 * Created on 12/11/2010, 10:00:14
 */

package InterfaceGrafica;

import facades.SistemaFacade;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import interfaces.Logavel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;

/**
 *
 * @author usuÃ¡rio
 */
public class AlterarLoginSenhaPanel extends javax.swing.JPanel implements KeyListener{
    private JTabbedPane tabbed;
    private JScrollPane scroll;
    private Logavel logavel;
    private SistemaFacade fachada = SistemaFacade.getInstance();

     @SuppressWarnings("deprecation")
    @Override
    public void keyPressed(KeyEvent e) {
            if (e.getKeyCode() == KeyEvent.VK_ENTER) {
                botaoOkActionPerformed(null);

            } else if (e.getKeyCode() == KeyEvent.VK_ESCAPE) {
                botaoFEcharAbaActionPerformed(null);
            }
    }

    @Override
    public void keyReleased(KeyEvent arg0) {
            // TODO Auto-generated method stub

    }

    @Override
    public void keyTyped(KeyEvent arg0) {
            // TODO Auto-generated method stub

    }

    
    /** Creates new form AlterarLoginSenhaPanel */
    public AlterarLoginSenhaPanel(Logavel logavel, JTabbedPane tabbed, JScrollPane scroll) {
        this.tabbed = tabbed;
        this.scroll = scroll;
        this.logavel = logavel;
        initComponents();

        scroll.addKeyListener(this);
        scroll.show();

        tabbed.addKeyListener(this);
        tabbed.show();

        this.addKeyListener(this);
        this.show();

        fieldLogin.addKeyListener(this);
        fieldLogin.show();

        botaoConfirma.addKeyListener(this);
        botaoConfirma.show();

        botaoFEcharAba.addKeyListener(this);
        botaoFEcharAba.show();

        botaoOk.addKeyListener(this);
        botaoOk.show();

        checkLogin.addKeyListener(this);
        checkLogin.show();

        checkSenha.addKeyListener(this);
        checkSenha.show();

        passConfirmaNovaSenha.addKeyListener(this);
        passConfirmaNovaSenha.show();

        passNovaSenha.addKeyListener(this);
        passNovaSenha.show();

        passSenha.addKeyListener(this);
        passSenha.show();


        camposSemSenhaConfirmada(false);
        reiniciaCampos();
    }

    private void reiniciaCampos() {
        fieldLogin.setText(null);
        passNovaSenha.setText(null);
        passConfirmaNovaSenha.setText(null);
        passSenha.setText(null);
        checkLogin.setSelected(false);
        checkSenha.setSelected(false);
    }

    private void camposSemSenhaConfirmada(boolean visivel) {
        jLabel2.setVisible(visivel);
        jLabel3.setVisible(false);
        jLabel3.setVisible(false);
        jLabel4.setVisible(false);
        jLabel5.setVisible(false);
        checkLogin.setVisible(visivel);
        checkSenha.setVisible(visivel);
        fieldLogin.setVisible(false);
        passConfirmaNovaSenha.setVisible(false);
        passNovaSenha.setVisible(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        passSenha = new javax.swing.JPasswordField();
        botaoOk = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        checkLogin = new javax.swing.JCheckBox();
        checkSenha = new javax.swing.JCheckBox();
        fieldLogin = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        passNovaSenha = new javax.swing.JPasswordField();
        jLabel4 = new javax.swing.JLabel();
        passConfirmaNovaSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        botaoFEcharAba = new javax.swing.JButton();
        botaoConfirma = new javax.swing.JButton();

        jLabel1.setText("Digite a senha");

        botaoOk.setText("OK");
        botaoOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOkActionPerformed(evt);
            }
        });

        jLabel2.setText("Selecione uma ou as duas opções que você deseja alterar");

        checkLogin.setText("Login");
        checkLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLoginActionPerformed(evt);
            }
        });

        checkSenha.setText("Senha");
        checkSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSenhaActionPerformed(evt);
            }
        });

        jLabel3.setText("Digite o novo login");

        jLabel4.setText("Digite a nova senha");

        jLabel5.setText("Confirme a nova senha");

        botaoFEcharAba.setText("Fechar aba");
        botaoFEcharAba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFEcharAbaActionPerformed(evt);
            }
        });

        botaoConfirma.setText("Confirmar Alterações");
        botaoConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(checkLogin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3))
                                    .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(checkSenha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel4))
                                    .addComponent(passNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel5))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                .addComponent(botaoFEcharAba)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(botaoConfirma))
                                            .addComponent(passConfirmaNovaSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoOk)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(passSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoOk))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkLogin)
                    .addComponent(fieldLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkSenha)
                    .addComponent(passNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(passConfirmaNovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoFEcharAba)
                    .addComponent(botaoConfirma))
                .addGap(100, 100, 100))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOkActionPerformed
        if(!passSenha.getText().isEmpty()) {
            if(logavel.getSenha().getSenha().equals(passSenha.getText())) {
                camposSemSenhaConfirmada(true);
                
            } else 
                JOptionPane.showMessageDialog(null, "Digite a senha corretamente",
                "Senha Inválida",
                JOptionPane.ERROR_MESSAGE);
        } else
            JOptionPane.showMessageDialog(null, "Digite a senha corretamente",
                "Senha Inválida",
                JOptionPane.ERROR_MESSAGE);

    }//GEN-LAST:event_botaoOkActionPerformed

    private void checkLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLoginActionPerformed
        if(checkLogin.isSelected()) {
            fieldLogin.setVisible(true);
            jLabel3.setVisible(true);
            
        } else {
            fieldLogin.setVisible(false);
            jLabel3.setVisible(false);
            fieldLogin.setText(null);
        }
    }//GEN-LAST:event_checkLoginActionPerformed

    private void checkSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSenhaActionPerformed
        if(checkSenha.isSelected()) {
            passNovaSenha.setVisible(true);
            passConfirmaNovaSenha.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
        } else {
            passNovaSenha.setVisible(false);
            passConfirmaNovaSenha.setVisible(false);
            passNovaSenha.setText(null);
            passConfirmaNovaSenha.setText(null);
            jLabel4.setVisible(false);
            jLabel5.setVisible(false);
        }
    }//GEN-LAST:event_checkSenhaActionPerformed

    private void botaoFEcharAbaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFEcharAbaActionPerformed
        tabbed.remove(scroll);
        reiniciaCampos();
    }//GEN-LAST:event_botaoFEcharAbaActionPerformed

    private void botaoConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmaActionPerformed
        try {
            if(checkLogin.isSelected() && checkSenha.isSelected()) {
                logavel = fachada.atualizaLogavel(logavel, fieldLogin.getText(),
                        passNovaSenha.getText(), passConfirmaNovaSenha.getText());
                JOptionPane.showMessageDialog(null, "Login e senha alterados",
                "Confirmado", JOptionPane.CLOSED_OPTION);
                reiniciaCampos();
                camposSemSenhaConfirmada(false);

            } else if(checkLogin.isSelected() && !checkSenha.isSelected()) {
                logavel = fachada.atualizaLogavel(logavel, fieldLogin.getText(),
                        logavel.getSenha().getSenha(), logavel.getSenha().getSenha());
                JOptionPane.showMessageDialog(null, "Login alterado",
                "Confirmado", JOptionPane.CLOSED_OPTION);
                reiniciaCampos();
                camposSemSenhaConfirmada(false);

            } else if(!checkLogin.isSelected() && checkSenha.isSelected()) {
                logavel = fachada.atualizaLogavel(logavel, logavel.getLogin().getLogin(),
                        passNovaSenha.getText(), passConfirmaNovaSenha.getText());
                JOptionPane.showMessageDialog(null, "Senha alterada",
                "Confirmado", JOptionPane.CLOSED_OPTION);
                reiniciaCampos();
                camposSemSenhaConfirmada(false);

            } else
                JOptionPane.showMessageDialog(null, "Selecione pelo menos uma opção",
                "Erro", JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(),
            "Erro",
            JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoConfirmaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoConfirma;
    private javax.swing.JButton botaoFEcharAba;
    private javax.swing.JButton botaoOk;
    private javax.swing.JCheckBox checkLogin;
    private javax.swing.JCheckBox checkSenha;
    private javax.swing.JTextField fieldLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPasswordField passConfirmaNovaSenha;
    private javax.swing.JPasswordField passNovaSenha;
    private javax.swing.JPasswordField passSenha;
    // End of variables declaration//GEN-END:variables

}
