/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FramePrincipal.java
 *
 * Created on 27/10/2010, 22:30:50
 */

package InterfaceGrafica;

import interfaces.Logavel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;

/**
 *
 * @author usuÃ¡rio
 */
public class FramePrincipal extends JFrame {
    private FormularioCliente formularioCliente;
    private BuscaCliente buscaCliente;
    private CriaContratos criaContratos;
    private EditarContrato editarContratos;
    private BuscaContratoPorData buscaContratosPorData;
    private PagamentoClientePanel pagamentoClientePanel;
    private TabelaDiaria tabelaDiaria;
    private TabelaMensal tabelaMensal;
    private Logavel logavel;
    private BuscaContratosPorStatus buscaStatus;
    private AlterarLoginSenhaPanel alterarLoginSena;
    private BuscaTabelaDiaria buscaTabelaDiaria;
    private BuscaTabelaMensal buscaTabelaMensal;
    private GeradorDeBoleto geradorDeBoleto;

    /** Creates new form FramePrincipal */
    public FramePrincipal(Logavel logavel) {
        this.logavel = logavel;
        initComponents();
        /*try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel");
        } catch (Exception ex) {
            setDefaultLookAndFeelDecorated(true);
        }*/
        SwingUtilities.updateComponentTreeUI(this);
        setVisible(true);
        setExtendedState(MAXIMIZED_BOTH);
        setTitle("Ortodontia e Estética");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBotoes = new javax.swing.JPanel();
        tabbed = new javax.swing.JTabbedPane();
        barraDeMenu = new javax.swing.JMenuBar();
        menuCliente = new javax.swing.JMenu();
        menuCadastrar = new javax.swing.JMenuItem();
        menuBuscar = new javax.swing.JMenuItem();
        MenuPagamento = new javax.swing.JMenuItem();
        menuContratos = new javax.swing.JMenu();
        menuOrtodontia = new javax.swing.JMenuItem();
        menuEditarContrato = new javax.swing.JMenuItem();
        menuBuscaContrato = new javax.swing.JMenuItem();
        MenuBucaStatus = new javax.swing.JMenuItem();
        menuRelatorios = new javax.swing.JMenu();
        menuBoleto = new javax.swing.JMenuItem();
        MenuTabelaDiaria = new javax.swing.JMenuItem();
        MenuTabelaMensal = new javax.swing.JMenuItem();
        MostraTabDiaria = new javax.swing.JMenuItem();
        MostraTabMensal = new javax.swing.JMenuItem();
        menuSistema = new javax.swing.JMenu();
        menuAlterarLoginSenha = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout panelBotoesLayout = new javax.swing.GroupLayout(panelBotoes);
        panelBotoes.setLayout(panelBotoesLayout);
        panelBotoesLayout.setHorizontalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        panelBotoesLayout.setVerticalGroup(
            panelBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        menuCliente.setText("Cliente");

        menuCadastrar.setText("Cadastrar");
        menuCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCadastrarActionPerformed(evt);
            }
        });
        menuCliente.add(menuCadastrar);

        menuBuscar.setText("Buscar");
        menuBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscarActionPerformed(evt);
            }
        });
        menuCliente.add(menuBuscar);

        MenuPagamento.setText("Pagamentos");
        MenuPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuPagamentoActionPerformed(evt);
            }
        });
        menuCliente.add(MenuPagamento);

        barraDeMenu.add(menuCliente);

        menuContratos.setText("Contratos");
        menuContratos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuContratosActionPerformed(evt);
            }
        });

        menuOrtodontia.setText("Criar Contrato(Ortodontia)");
        menuOrtodontia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuOrtodontiaActionPerformed(evt);
            }
        });
        menuContratos.add(menuOrtodontia);

        menuEditarContrato.setText("Editar Contrato");
        menuEditarContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarContratoActionPerformed(evt);
            }
        });
        menuContratos.add(menuEditarContrato);

        menuBuscaContrato.setText("Busca por Data");
        menuBuscaContrato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBuscaContratoActionPerformed(evt);
            }
        });
        menuContratos.add(menuBuscaContrato);

        MenuBucaStatus.setText("Buscar Por Status");
        MenuBucaStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBucaStatusActionPerformed(evt);
            }
        });
        menuContratos.add(MenuBucaStatus);

        barraDeMenu.add(menuContratos);

        menuRelatorios.setText("Relatório");

        menuBoleto.setText("Gerar Boleto");
        menuBoleto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBoletoActionPerformed(evt);
            }
        });
        menuRelatorios.add(menuBoleto);

        MenuTabelaDiaria.setText("Tabela Diária");
        MenuTabelaDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTabelaDiariaActionPerformed(evt);
            }
        });
        menuRelatorios.add(MenuTabelaDiaria);

        MenuTabelaMensal.setText("Tabela Mensal");
        MenuTabelaMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuTabelaMensalActionPerformed(evt);
            }
        });
        menuRelatorios.add(MenuTabelaMensal);

        MostraTabDiaria.setText("Mostrar Tabela Diaria");
        MostraTabDiaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraTabDiariaActionPerformed(evt);
            }
        });
        menuRelatorios.add(MostraTabDiaria);

        MostraTabMensal.setText("Mostrar Tabela Mensal");
        MostraTabMensal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MostraTabMensalActionPerformed(evt);
            }
        });
        menuRelatorios.add(MostraTabMensal);

        barraDeMenu.add(menuRelatorios);

        menuSistema.setText("Sistema");

        menuAlterarLoginSenha.setText("Alterar Login/Senha");
        menuAlterarLoginSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAlterarLoginSenhaActionPerformed(evt);
            }
        });
        menuSistema.add(menuAlterarLoginSenha);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuSistema.add(menuLogout);

        barraDeMenu.add(menuSistema);

        setJMenuBar(barraDeMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tabbed, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCadastrarActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        formularioCliente = new FormularioCliente(tabbed, s);
        s.setViewportView(formularioCliente);
        tabbed.addTab("Cadastrar Cliente", s);
        System.gc();
}//GEN-LAST:event_menuCadastrarActionPerformed

    private void menuBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscarActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        buscaCliente = new BuscaCliente(tabbed, s);
        s.setViewportView(buscaCliente);
        tabbed.addTab("Buscar Clientes", s);
        System.gc();
    }//GEN-LAST:event_menuBuscarActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        System.gc();
        JOptionPane.showMessageDialog(null, "Você saiu do sistema",
                "Logout",
                JOptionPane.CLOSED_OPTION);
        dispose();
        new Login();
        System.gc();
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuContratosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuContratosActionPerformed
        
    }//GEN-LAST:event_menuContratosActionPerformed

    private void menuOrtodontiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuOrtodontiaActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        criaContratos = new CriaContratos(tabbed, s);
        s.setViewportView(criaContratos);
        tabbed.addTab("Criar Contrato", s);
        System.gc();
    }//GEN-LAST:event_menuOrtodontiaActionPerformed

    private void menuEditarContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarContratoActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        editarContratos = new EditarContrato(tabbed, s);
        s.setViewportView(editarContratos);
        tabbed.addTab("Editar contratos", s);
        System.gc();
    }//GEN-LAST:event_menuEditarContratoActionPerformed

    private void menuBuscaContratoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBuscaContratoActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        buscaContratosPorData = new BuscaContratoPorData(tabbed, s);
        s.setViewportView(buscaContratosPorData);
        tabbed.addTab("Busca contratos por data", s);
        System.gc();
    }//GEN-LAST:event_menuBuscaContratoActionPerformed

    private void MenuPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuPagamentoActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        pagamentoClientePanel = new PagamentoClientePanel(tabbed, s);
        s.setViewportView(pagamentoClientePanel);
        tabbed.addTab("Pagamento", s);
        System.gc();
    }//GEN-LAST:event_MenuPagamentoActionPerformed

    private void MenuTabelaDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTabelaDiariaActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        tabelaDiaria = new TabelaDiaria(tabbed, s);
        s.setViewportView(tabelaDiaria);
        tabbed.addTab("Tabela Diária", s);
        System.gc();
    }//GEN-LAST:event_MenuTabelaDiariaActionPerformed

    private void MenuTabelaMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuTabelaMensalActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        tabelaMensal = new TabelaMensal(tabbed, s);
        s.setViewportView(tabelaMensal);
        tabbed.addTab("Tabela Mensal", s);
        System.gc();
    }//GEN-LAST:event_MenuTabelaMensalActionPerformed

    private void MenuBucaStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBucaStatusActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        buscaStatus = new BuscaContratosPorStatus(tabbed, s);
        s.setViewportView(buscaStatus);
        tabbed.addTab("Busca Contrato Por Status", s);
        System.gc();
    }//GEN-LAST:event_MenuBucaStatusActionPerformed

    private void menuAlterarLoginSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAlterarLoginSenhaActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        alterarLoginSena = new AlterarLoginSenhaPanel(logavel,tabbed, s);
        s.setViewportView(alterarLoginSena);
        tabbed.addTab("Alterar Login/Senha", s);
        System.gc();
    }//GEN-LAST:event_menuAlterarLoginSenhaActionPerformed

    private void MostraTabDiariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraTabDiariaActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        buscaTabelaDiaria = new BuscaTabelaDiaria(tabbed, s);
        s.setViewportView(buscaTabelaDiaria);
        tabbed.addTab("Mostra Tabela Diaria", s);
        System.gc();
    }//GEN-LAST:event_MostraTabDiariaActionPerformed

    private void menuBoletoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBoletoActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        geradorDeBoleto = new GeradorDeBoleto(tabbed, s);
        s.setViewportView(geradorDeBoleto);
        tabbed.addTab("Gerador De Boletos", s);
        System.gc();
    }//GEN-LAST:event_menuBoletoActionPerformed

    private void MostraTabMensalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MostraTabMensalActionPerformed
        System.gc();
        JScrollPane s = new JScrollPane();
        buscaTabelaMensal = new BuscaTabelaMensal(tabbed, s);
        s.setViewportView(buscaTabelaMensal);
        tabbed.addTab("Buscar Tabelas Mensais", s);
        System.gc();
    }//GEN-LAST:event_MostraTabMensalActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuBucaStatus;
    private javax.swing.JMenuItem MenuPagamento;
    private javax.swing.JMenuItem MenuTabelaDiaria;
    private javax.swing.JMenuItem MenuTabelaMensal;
    private javax.swing.JMenuItem MostraTabDiaria;
    private javax.swing.JMenuItem MostraTabMensal;
    private javax.swing.JMenuBar barraDeMenu;
    private javax.swing.JMenuItem menuAlterarLoginSenha;
    private javax.swing.JMenuItem menuBoleto;
    private javax.swing.JMenuItem menuBuscaContrato;
    private javax.swing.JMenuItem menuBuscar;
    private javax.swing.JMenuItem menuCadastrar;
    private javax.swing.JMenu menuCliente;
    private javax.swing.JMenu menuContratos;
    private javax.swing.JMenuItem menuEditarContrato;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuOrtodontia;
    private javax.swing.JMenu menuRelatorios;
    private javax.swing.JMenu menuSistema;
    private javax.swing.JPanel panelBotoes;
    private javax.swing.JTabbedPane tabbed;
    // End of variables declaration//GEN-END:variables

}
